#! /bin/sh

# App settings
export TERM="alacritty"
export LAUNCH="rofi -show run"
export CALC="rofi -show calc -modi calc -no-show-match -no-sort -lines 2"
export BROWSE="vivaldi-stable"
export MUSIC="spotify"
export DISCORD="discord"
export CONF="$TERM -e nvim ~/.config"
export CODE="emacs"
export GAME="steam"
export DOCS="$TERM -e nvim ~/Documents"
export SYS="$TERM -e gotop -p"
export NET="$TERM -e nmtui-connect"
export VIS="$TERM -e cava"

# Kill
killall picom
killall feh
killall dunst
killall sxhkd
killall polybar
killall xss-lock

# Autostart
xss-lock -l -- betterlockscreen --lock dimblur &
feh --bg-fill $HOME/Pictures/Wallpapers/background5.png &
dunst &
sxhkd &
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar main &
done 

# Monitor
if [ "$(hostname)" = "michael-desktop" ]
then   
    bspc monitor DP-0 -d 1 2 3
    bspc monitor HDMI-0 -d 4 5 6
    bspc monitor DP-3 -d 7 8 9
    picom &
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
    picom --backend glx &
fi

# Rules
bspc rule -a Emacs state=tiled

# Window config
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          10

# Layout config
bspc config automatic_scheme alternate
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color config
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#81a1c1"
bspc config active_border_color     "#4c566a"
bspc config presel_feedback_color	"#81a1c1"
