#!/bin/sh

# App settings
export TERM="kitty"
export LAUNCH="rofi -show drun"
export CALC="rofi -show calc -modi calc -no-show-match -no-sort -lines 2"
export BROWSE="firefox-developer-edition"
export DISCORD="discord"
export EDIT="code-oss"
export GAME="steam"
export MUSIC="spotify"
export SYNC="$TERM -e fish -i -c 'code-sync -x'"
export FILE="$TERM -e ranger"
export SYS="$TERM -e gotop -p"
export NET="$TERM -e sh -c 'bspc node -t floating; sleep 0.1; nmtui-connect'"

# Kill
killall picom
killall feh
killall dunst
killall sxhkd
killall polybar
killall xss-lock

# Autostart
xss-lock -l -- betterlockscreen --lock dimblur &
feh --bg-fill $HOME/.config/wallpaper.png &
dunst &
sxhkd &
picom --experimental-backends &
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar main &
done


# Monitor
if [ "$(hostname)" = "michael-desktop" ]
then   
    bspc monitor DP-0 -d 1 2 3
    bspc monitor HDMI-0 -d 4 5 6
    bspc monitor DP-3 -d 7 8 9
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# Window config
bspc config focus_follows_pointer true
bspc config border_width         0
bspc config window_gap          24

# Layout config
bspc config automatic_scheme alternate
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Resize and move
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 resize_side

# Color config
bspc config normal_border_color     "#2e3440"
bspc config focused_border_color	"#2e3440"
bspc config active_border_color     "#2e3440"
bspc config presel_feedback_color	"#81a1c1"
