#!/bin/sh
# rofi power menu

chosen=$(echo "Lock\nSuspend\nReboot\nShutdown" | rofi -dmenu -i -lines 4)
if [ $chosen = "Lock" ]; then
    betterlockscreen --lock -- --timestr '%l:%H:%S'
elif [ $chosen = "Suspend" ]; then
    sudo zzz
elif [ $chosen = "Reboot" ]; then
    sudo shutdown -r now
elif [ $chosen = "Shutdown" ]; then
    sudo shutdown -h now
fi
