# history
HISTFILE=~/.cache/zsh_history
SAVEHIST=50
HISTSIZE=50

# powerlevel9k
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_VCS_HIDE_TAGS=true
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(host dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs time)
