# zsh config home
ZHOME="/home/mbednarek360"

# load aliases
source $ZHOME/.config/zsh/aliases.sh

# load plugins
source $ZHOME/.cache/zsh/plugins.sh

# load options
source $ZHOME/.config/zsh/options.sh
